/*
    ONLINE_SALE: 온라인 판매 테이블, OFFLINE_SALE: 오프라인 판매 테이블
    목표:2022년 3월의 오프라인/온라인 상품 판매 데이터 정보 출력,
    OFFLINE_SALE테이블의 판매데이터의 USER_ID값은 NULL로 표시
    출력: SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
    각각 조건에 맞춰서 SELECT문 두개로 구한다음 UNION ALL로 합치기
*/
SELECT
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE
WHERE
    YEAR(SALES_DATE) = 2022 
    AND MONTH(SALES_DATE) = 3

UNION ALL

SELECT
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM
    OFFLINE_SALE
WHERE
    YEAR(SALES_DATE) = 2022 
    AND MONTH(SALES_DATE) = 3
ORDER BY
    SALES_DATE, 
    PRODUCT_ID, 
    USER_ID