/*
    ONLINE_SALE: 온라인 상품 판매 정보, OFFLINE_SALE: 오프라인 상품 판매 정보
    2022년 3월의 오프라인/온라인 상품 판매 정보 출력, 오프라인 USER_ID는 NULL
    출력: SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
    각 조건에 맞게 필터링을 해서 UNION ALL로 출력
*/
SELECT 
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE
WHERE
    SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"

UNION

SELECT
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT
FROM
    OFFLINE_SALE
WHERE
    SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"
ORDER BY
    SALES_DATE, 
    PRODUCT_ID, 
    USER_ID