-- 코드를 입력하세요
WITH CTE AS (
    SELECT CRCC.CAR_ID, CAR_TYPE, HISTORY_ID, DAILY_FEE, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_CAR CRCC
        LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
                                                          AND START_DATE <= "2022-11-30" 
                                                          AND END_DATE >= "2022-11-01"
    WHERE (CAR_TYPE = "세단" OR CAR_TYPE = "SUV") AND HISTORY_ID IS NULL
),
CTE2 AS (
    SELECT C.CAR_ID,
           C.CAR_TYPE, 
           FLOOR((C.DAILY_FEE * (1 - DISCOUNT_RATE * 0.01) * 30)) AS FEE
    FROM CTE C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP ON C.CAR_TYPE = CRCDP.CAR_TYPE
    WHERE duration_type = "30일 이상"
    HAVING FEE <= 2000000 AND FEE >= 500000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
)
SELECT *
FROM CTE2