# ANIMAL_INS는 동물 보호소에 들어온 동물의 정보 테이블, ANIMAL_OUTS는 동물 보호소에서 입양 보낸 동물의 정보 테이블
# 보호소에서 중성화 수술을 거친 동물 정보 조회
# ANIMAL_ID, ANIMAL_TYPE, NAME 조회, NAME순으로 ORDER BY
# 두 테이블을 아이디를 기준으로 조인, SEX_UPON_INTAKE와 SEX_UPON_OUTCOME이 다를경우 프린트
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE SEX_UPON_INTAKE <> SEX_UPON_OUTCOME
ORDER BY AI.ANIMAL_ID