/*
    목표:서울에 위치한 식당들의 정보 출력
    출력: REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
    ORDER BY SCORE DESC, FAVORITES DESC
    두 테이블을 REST_ID를 기준으로 조인, 그 이후 필요한 정보들을 출력하는데, SCORE는
    ROUND()로 2자리로 반올림, WHERE절에서 ADDRESS가 서울인 텍스트로 출력
*/
SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO RI
    JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE
    LEFT(ADDRESS, 2) = "서울"
GROUP BY
    RI.REST_ID
ORDER BY 
    SCORE DESC, 
    FAVORITES DESC