# Write your MySQL query statement below
SELECT P.PRODUCT_ID, PRODUCT_NAME
FROM PRODUCT P
    JOIN SALES S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY PRODUCT_ID
HAVING MIN(SALE_DATE) >= "2019-01-01" AND MAX(SALE_DATE) <="2019-03-31"