# 입양을 간 기록은 있는데, 보호소 들어온 기록이 없는 동물의 정보 조회
# ANIMAL_INS & ANIMAL_OUTS RIGHT 조인, 
# ANIMAL_INS의 DATETIME이 NULL일경우, 그 ANIMAL_ID 출력
# ANIMAL_ID, NAME 출력, ORDER BY ANIMAL_ID
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AI
    RIGHT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME IS NULL
ORDER BY AO.ANIMAL_ID