# 노선별로 노선, 총 누계 거리(역 사이 거리 총 합), 평균 역 사이 거리를 조회
# ROUTE, TOTAL_DISTANCE, AVERAGE_DISTANCE 출력, ORDER BY TOTAL_DISTANCE DESC
# GROUP BY ROUTE하고, SUM()과 AVG()로 총 합 과 평균 구하기
# CONCAT으로 km붙여야함 
SELECT ROUTE, 
       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), "km") AS TOTAL_DISTANCE,
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC