# Upload용 커맨트
WITH CTE AS (
    SELECT COUNT(*) AS TOTAL_COUNT
    FROM USER_INFO UI
    WHERE JOINED >= "2021-01-01" AND JOINED <= "2021-12-31"
),
CTE2 AS (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO UI
        JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
    WHERE JOINED >= "2021-01-01" AND JOINED <= "2021-12-31"
    GROUP BY YEAR, MONTH
)
SELECT YEAR, MONTH, PURCHASED_USERS, 
       ROUND(PURCHASED_USERS / (SELECT TOTAL_COUNT FROM CTE), 1) AS PURCHASED_RATIO
FROM CTE2
ORDER BY YEAR ASC, MONTH ASC