/*
    2021년 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년, 월 별로 출력
    출력: YEAR, MONTH, PURCHASED_USERS, PURCHASED_RATIO
    ORDER BY YEAR, MONTH
    비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
    CTE로 먼저 2021년에 가입한 전체 회원 수 카운트,
    두번째 CTE에서 USER_ID를 기준으로 USER_INFO와 조인, YEAR과 MONTH별로 카운트
    밖에 SELECT문에서 마무리
*/
WITH CTE AS (
    SELECT COUNT(*) AS TOTAL_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
CTE2 AS (
    SELECT 
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT UI.USER_ID) AS PURCHASED_USERS
    FROM USER_INFO UI
        JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
    WHERE YEAR(JOINED) = 2021
    GROUP BY YEAR, MONTH
)
SELECT 
    *,
    ROUND(PURCHASED_USERS / (SELECT TOTAL_COUNT FROM CTE), 1) AS PURCHASED_RATIO
FROM CTE2
ORDER BY YEAR, MONTH