# 각 분기별 분화된 대장균의 개체의 총 수를 출력
# 출력 QUARTER (Q를 붙혀서), ECOLI_COUNT, ORDER BY QUARTER
# CTE에서 CASE WHEN으로 QUARTER 만들기, 밖에 SELECT문에서 COUNT
WITH CTE AS (
    SELECT *,
           CASE
                WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN "1Q"
                WHEN MONTH(DIFFERENTIATION_DATE) >= 4 AND 
                     MONTH(DIFFERENTIATION_DATE) < 7 THEN "2Q"
                WHEN MONTH(DIFFERENTIATION_DATE) >= 7 AND 
                     MONTH(DIFFERENTIATION_DATE) < 10 THEN "3Q"
                ELSE "4Q"
            END AS QUARTER
    FROM ECOLI_DATA
)
SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM CTE
GROUP BY QUARTER
ORDER BY QUARTER