# ANIMAL_INS: 동물 보호소에 들어온 동물의 정보, ANIMAL_OUTS: 입양보낸 동물 정보
# 입양 못간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일 조회
# NAME, DATETIME 출력, ORDER BY DATETIME
# ANIMAL_INS에서 NAME, DATETIME 출력, WHERE문에서 서브쿼리로 ANIMAL_ID 필터링
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3