/*
    FOOD_PRODUCT: 식품 정보 테이블, FOOD_ORDER: 식품 주문 정보 테이블
    생산일자가 2022년 5월인 식품의 정보를 출력해달라
    출력: PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES(PRICE * AMOUNT)
    ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
    CTE로 FOOD_ORDER 테이블에서 PRODUCE_DATE를 5월자 생산된걸로 필터링 해놓고,
    PRODUCT_ID별로 GROUP BY 해서 SUM(AMOUNT)
    SELECT문에서 FOOD_PRODUCT랑 CTE를 JOIN, PRICE랑 AMOUNT 곱해서 출력
*/
WITH CTE AS (
    SELECT 
        PRODUCT_ID, 
        SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM 
        FOOD_ORDER
    WHERE 
        YEAR(PRODUCE_DATE) = 2022 AND
        MONTH(PRODUCE_DATE) = 5
    GROUP BY
        PRODUCT_ID
)
SELECT 
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME, 
    (FP.PRICE * C.TOTAL_AMOUNT) AS TOTAL_SALES
FROM 
    CTE C
    LEFT JOIN FOOD_PRODUCT FP ON C.PRODUCT_ID = FP.PRODUCT_ID
ORDER BY 
    TOTAL_SALES DESC, 
    FP.PRODUCT_ID ASC