# Upload용 커맨트
WITH CTE AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
    GROUP BY PRODUCT_ID 
)

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, TOTAL_AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FP
    JOIN CTE C ON FP.PRODUCT_ID = C.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC