WITH CTE AS (
    SELECT C.CAR_ID, C.CAR_TYPE, DAILY_FEE, HISTORY_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL,
           CASE
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 AND DATEDIFF(END_DATE,                      START_DATE) + 1 < 90 THEN "30일 이상"
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 AND DATEDIFF(END_DATE,                      START_DATE) + 1 < 30 THEN "7일 이상"
           END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C2 ON C.CAR_ID = C2.CAR_ID
    WHERE CAR_TYPE = "트럭"
)
SELECT HISTORY_ID,
       CASE
            WHEN C.DURATION_TYPE = "7일 이상" 
            THEN ROUND(((100 - CP.DISCOUNT_RATE) / 100) * DAILY_FEE * RENTAL, 0)
            WHEN C.DURATION_TYPE = "30일 이상" 
            THEN ROUND(((100 - CP.DISCOUNT_RATE) / 100) * DAILY_FEE * RENTAL, 0)
            WHEN C.DURATION_TYPE = "90일 이상" 
            THEN ROUND(((100 - CP.DISCOUNT_RATE) / 100) * DAILY_FEE * RENTAL, 0)
            ELSE ROUND(DAILY_FEE * RENTAL,0) 
        END AS FEE
FROM CTE C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP ON 
              C.DURATION_TYPE = CP.DURATION_TYPE AND C.CAR_TYPE = CP.CAR_TYPE
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC