/*
    CAR_RENTAL_COMPANY_CAR: 대여중인 자동차 정보, CAR_RENTAL_COMPANY_RENTAL_HISTORY: 대여 기록 정보
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN: 대여기간 할인정책 테이블
    자동차 종류가 트럭인 자동차의 대여기록에 대해서, 대여기록별로 대여금액 구하기
    출력: HISTORY_ID, FEE(대여기록 별 대여금액 계산한거), ORDER BY FEE DESC, HISTORY_ID DESC
    CTE문에서 CAR_RENTAL_COMPANY_CAR랑 CAR_RENTAL_COMPANY_RENTAL_HISTORY를 조인, CAR_TYPE이 '트럭'인걸로 필터링
    DATEDIFF(END_DATE, START_DATE) AS duration, 그리고 Duration Type 구하기
    밖에서 CTE랑 CAR_RENTAL_COMPANY_DISCOUNT_PLAN을 조인 할껀데, CAR_TYPE과 Duration type을 기준으로, 그리고 트럭인것만
    SELECT문에서 FEE를 구하기
*/
WITH CTE AS (
    SELECT
        DISTINCT CRCRH.HISTORY_ID,
        CRCC.CAR_TYPE,
        CRCC.DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 AND 
                 DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 AND
                 DATEDIFF(END_DATE, START_DATE) + 1 THEN "7일 이상"
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_CAR CRCC
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
    WHERE
        CRCC.CAR_TYPE = '트럭'
)
SELECT
    DISTINCT C.HISTORY_ID,
    CASE
        WHEN C.DURATION_TYPE = '7일 이상' 
        THEN ROUND(((100 - CRCDP.DISCOUNT_RATE) / 100) * DAILY_FEE * DURATION, 0)
        WHEN C.DURATION_TYPE = '30일 이상' 
        THEN ROUND(((100 - CRCDP.DISCOUNT_RATE) / 100) * DAILY_FEE * DURATION, 0)
        WHEN C.DURATION_TYPE = '90일 이상' 
        THEN ROUND(((100 - CRCDP.DISCOUNT_RATE) / 100) * DAILY_FEE * DURATION, 0)
        ELSE ROUND(DAILY_FEE * DURATION, 0)
    END AS FEE
    
FROM
    CTE C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP ON C.CAR_TYPE = CRCDP.CAR_TYPE
                                                    AND C.DURATION_TYPE = CRCDP.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC