/*
    FIRST_HALF: 상반기 주문 정보, JULY: 7월 아이스크림 주문 정보
    7월 아이스크림 총 주문량과 상반기 아이스크림 총 주문량 더한값이 큰 순서대로 상위 3개의 맛 조회
    출력 FLAVOR, ORDER BY 큰순서
    JOIN을 해주는데, FLAVOR 기준으로 합치고, ORDER BY에서 SUM(TOTAL_ORDER + TOTAL_ORDER) DESC
    LIMIT 3
*/
SELECT J.FLAVOR
FROM FIRST_HALF FH
    RIGHT JOIN JULY J ON FH.SHIPMENT_ID = J.SHIPMENT_ID
GROUP BY FLAVOR
ORDER BY SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3