/*
    목표:7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량 상위 3개 맛 조회
    JULY랑 FIRST_HALF를 LEFT_JOIN SHIPMENT_ID를 기준으로,
    GROUP BY FLAVOR
    ORDER BY SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
    LIMIT 3하면 될것 같아요
*/
SELECT
    FH.FLAVOR
FROM
    JULY J
    LEFT JOIN FIRST_HALF FH ON J.SHIPMENT_ID = FH.SHIPMENT_ID
GROUP BY
    J.FLAVOR
ORDER BY
    SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3