-- PATIENT: 환자 정보, DOCTOR: 의사 정보, APPOINTMENT: 진료 예약목록
# 출력해야 하는 정보: APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD
# 2022년 4월 13일 취소되지 않은 CS 진료예약 내역(APNT_CNCL_YMD = NULL), ORDER BY APNT_YMD ASC
# CTE에서 DOCTOR & APPOINTMENT 조인, MCDP_CD가 CS인것과, 2022년 4월 13일 예약으로 필터링
# 밖에서 PATIENT 테이블과 조인
WITH CTE AS (
    SELECT APNT_YMD, PT_NO, APNT_NO, DR_NAME, A.MCDP_CD
    FROM APPOINTMENT A
        LEFT JOIN DOCTOR D ON A.MCDP_CD = D.MCDP_CD
                      AND A.MDDR_ID = D.DR_ID
    WHERE A.MCDP_CD = "CS" 
          AND APNT_CNCL_YN = "N"
          AND APNT_YMD >= "2022-04-13" AND APNT_YMD < "2022-04-14"
)
SELECT APNT_NO, PT_NAME, P.PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM CTE C
    JOIN PATIENT P ON C.PT_NO = P.PT_NO
ORDER BY APNT_YMD ASC