/*
    목표: PATIENT, DOCTOR, APPOINTMENT 테이블에서 2022/04/13 취소되지 않은 흉부외과 진료 예약 내역 출력
    출력: APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD ORDER BY APNT_YMD
    APPOINTMENT와 DOCTOR를 MDDR_ID와 DR_ID 기준으로 조인, APPOINTMENT와 PATIENT를 PT_NO기준으로 조인
    WHERE 절에서 DATE_FORMAT(APTNT_YMD)로 2022-04-13로 필터링 하고,
    APNT_CNCL_YN이 "N", 그리고 MCDP_CD가 "CS"인것으로 필터링 후 출력
*/
SELECT
    A.APNT_NO,
    P.PT_NAME,
    A.PT_NO,
    A.MCDP_CD,
    D.DR_NAME,
    A.APNT_YMD
FROM
    APPOINTMENT A
    JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID AND A.MCDP_CD = "CS"
    JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE
    DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND A.APNT_CNCL_YN = 'N'
ORDER BY
    A.APNT_YMD