# Upload용 커맨트
-- USED_GOODS_BOARD랑 USED_GOODS_USER 테이블 JOIN ON WRITER_ID랑 USER_ID를 기준
-- STATUS가 DONE, PRICE가 700000 >= 이여야 하기 때문에 WHERE절에 넣어서 진행
-- 만약 오류가 날 경우 CTE로 따로 조건을 넣은 테이블을 만들어서 다시 조인 후 진행해보겠습니다.

WITH CTE AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
)
SELECT UGU.USER_ID, NICKNAME, TOTAL_SALES
FROM CTE
    JOIN USED_GOODS_USER UGU ON CTE.WRITER_ID = UGU.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC