# CTE로 멤버 아이디 별 카운트, 가장 높은 숫자를 가진 멤버만
# 그후 밖에서 멤버 아이디로 조인, 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
# 리뷰 작성일 오름차순, 리뷰 텍스트 오름차순
WITH CTE AS (
    SELECT MEMBER_ID, COUNT(*) AS cnts
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY cnts DESC
    LIMIT 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT MEMBER_ID FROM CTE)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC