-- 2022/08부터 2022/10까지 총 대여횟수가 5회 이상인 자동차에 대해 총 대여횟수 출력
# 대여 MONTH, CAR_ID, 대여횟수(RECORDS) 출력, ORDER BY MONTH, CAR_ID DESC
# GROUP BY MONTH(START_DATE), CAR_ID로 CAR_ID 카운트
# WHERE 절에선 START_DATE을 8월 이후, 10월 이전으로 필터링
WITH CTE AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
SELECT MONTH(START_DATE) AS MONTH, 
       CAR_ID, 
       COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE BETWEEN "2022-08-01" AND "2022-10-31")
AND CAR_ID IN (SELECT * FROM CTE)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC