SELECT CUSTOMER_ID
FROM CUSTOMER C
    JOIN PRODUCT P ON C.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY CUSTOMER_ID
HAVING COUNT(DISTINCT P.PRODUCT_KEY) = (SELECT COUNT(*)
                                        FROM PRODUCT)