# Upload용 커맨트
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
       CASE 
            WHEN UG.STATUS = "DONE" THEN  "거래완료"
            WHEN UG.STATUS = "SALE" THEN "판매중"
       ELSE '예약중'
       END AS STATUS
FROM USED_GOODS_BOARD AS UG
WHERE CREATED_DATE = "2022-10-05"
ORDER BY BOARD_ID DESC