# Upload용 커맨트
SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS UG
    JOIN USED_GOODS_FILE AS UF ON UG.BOARD_ID = UF.BOARD_ID
WHERE UG.VIEWS = (SELECT VIEWS 
                  FROM USED_GOODS_BOARD 
                  ORDER BY VIEWS DESC
                  LIMIT 1)
ORDER BY FILE_ID DESC