-- 코드를 입력하세요
WITH CTE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
SELECT FP.CATEGORY, C.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
    JOIN CTE C ON FP.CATEGORY = C.CATEGORY
               AND FP.PRICE = C.MAX_PRICE
WHERE FP.CATEGORY IN ("과자", '국', '김치', '식용유')
ORDER BY FP.PRICE DESC