-- 코드를 작성해주세요
WITH CTE AS (
    SELECT FISH_TYPE, 
           COUNT(*) AS FISH_COUNT, 
           SUM(CASE WHEN LENGTH > 10 THEN LENGTH ELSE 10 END) /
           COUNT(*) AS LENGTH_AVG,
           MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM CTE
WHERE LENGTH_AVG >=  33
ORDER BY FISH_TYPE ASC