WITH CTE AS (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT 
    CASE
        WHEN SKILL_CODE & (SELECT * FROM CTE)
        AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'python')
        THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') 
        THEN 'B'
    WHEN SKILL_CODE & (SELECT * FROM CTE)
        THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS D
    JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID